export const PERMISSIONS = {
  TENANTS_CREATE: 'tenants:create',
  TENANTS_READ_CURRENT: 'tenants:read_current',
  TENANT_SETTINGS_UPDATE: 'tenant_settings:update',

  USERS_CREATE: 'users:create',
  USERS_READ: 'users:read',
  USERS_UPDATE: 'users:update',
  USERS_DELETE: 'users:delete',
  USERS_IMPORT: 'users:import',

  TEAMS_CREATE: 'teams:create',
  TEAMS_READ: 'teams:read',
  TEAMS_UPDATE: 'teams:update',
  TEAMS_MEMBERS_WRITE: 'teams:members:write',

  USER_ROLES_ASSIGN: 'user_roles:assign',
  ROLES_READ: 'roles:read',
  PERMISSIONS_READ: 'permissions:read',

  OFFICE_LOCATIONS_CREATE: 'office_locations:create',
  OFFICE_LOCATIONS_READ: 'office_locations:read',
  OFFICE_IPS_CREATE: 'office_ips:create',
  OFFICE_IPS_READ: 'office_ips:read',
  OFFICE_POLICY_CHECK: 'office_policy:check',

  NOTIFICATION_SELF_READ: 'notification_preferences:self:read',
  NOTIFICATION_SELF_UPDATE: 'notification_preferences:self:update',

  PROJECTS_CREATE: 'projects:create',
  PROJECTS_READ: 'projects:read',
  PROJECTS_UPDATE: 'projects:update',
  PROJECTS_DELETE: 'projects:delete',
  PROJECTS_MEMBERS_WRITE: 'projects:members:write',
  PROJECTS_COSTS_WRITE: 'projects:costs:write',
  PROJECTS_BURN_READ: 'projects:burn:read',
  PROJECTS_COST_SUMMARY_READ: 'projects:cost_summary:read',

  TIME_ENTRIES_CREATE: 'time_entries:create',
  TIME_ENTRIES_READ: 'time_entries:read',
  TIME_ENTRIES_ADJUST: 'time_entries:adjust',
  TIME_ENTRIES_UNLOCK: 'time_entries:unlock',
  TIME_ENTRIES_SUMMARY_READ: 'time_entries:summary:read',
  TIME_ENTRIES_MANAGER_BULK: 'time_entries:manager_bulk',

  MILESTONES_CREATE: 'milestones:create',
  MILESTONES_READ: 'milestones:read',
  MILESTONES_UPDATE: 'milestones:update',
  MILESTONES_DELETE: 'milestones:delete',

  TASK_STATUSES_CREATE: 'task_statuses:create',
  TASK_STATUSES_READ: 'task_statuses:read',
  TASK_STATUSES_UPDATE: 'task_statuses:update',
  TASK_STATUSES_DELETE: 'task_statuses:delete',

  TASK_WORKFLOWS_CREATE: 'task_workflows:create',
  TASK_WORKFLOWS_READ: 'task_workflows:read',

  TASKS_CREATE: 'tasks:create',
  TASKS_READ: 'tasks:read',
  TASKS_UPDATE: 'tasks:update',
  TASKS_DELETE: 'tasks:delete',
  TASKS_STATUS_UPDATE: 'tasks:status:update',
  TASKS_KANBAN_READ: 'tasks:kanban:read',
  TASKS_BULK_UPDATE: 'tasks:bulk:update',
  TASKS_DEPENDENCIES_WRITE: 'tasks:dependencies:write',
  TASKS_COMMENTS_CREATE: 'tasks:comments:create',
  TASKS_COMMENTS_READ: 'tasks:comments:read',

  ATTACHMENTS_PRESIGNED_URL: 'attachments:presigned_url:create',
  ATTACHMENTS_CONFIRM_UPLOAD: 'attachments:confirm_upload',
  ATTACHMENTS_READ: 'attachments:read',

  ATTENDANCE_CHECK_IN: 'attendance:check_in',
  ATTENDANCE_CHECK_OUT: 'attendance:check_out',
  ATTENDANCE_TODAY_READ: 'attendance:today:read',
  ATTENDANCE_REPORT_READ: 'attendance:report:read',
  ATTENDANCE_REGULARIZATION_CREATE: 'attendance_regularization:create',
  ATTENDANCE_REGULARIZATION_READ: 'attendance_regularization:read',
  ATTENDANCE_REGULARIZATION_APPROVE: 'attendance_regularization:approve',
  ATTENDANCE_REGULARIZATION_REJECT: 'attendance_regularization:reject',

  LEAVE_TYPES_CREATE: 'leave_types:create',
  LEAVE_TYPES_READ: 'leave_types:read',
  LEAVE_POLICIES_CREATE: 'leave_policies:create',
  LEAVE_BALANCE_ME_READ: 'leave_balance:me:read',
  LEAVE_BALANCE_USER_READ: 'leave_balance:user:read',
  LEAVE_REQUESTS_CREATE: 'leave_requests:create',
  LEAVE_REQUESTS_READ: 'leave_requests:read',
  LEAVE_REQUESTS_APPROVE: 'leave_requests:approve',
  LEAVE_REQUESTS_REJECT: 'leave_requests:reject',

  WFH_POLICIES_CREATE: 'wfh_policies:create',
  WFH_BALANCE_ME_READ: 'wfh_balance:me:read',
  WFH_BALANCE_USER_READ: 'wfh_balance:user:read',
  WFH_REQUESTS_CREATE: 'wfh_requests:create',
  WFH_REQUESTS_READ: 'wfh_requests:read',
  WFH_REQUESTS_APPROVE: 'wfh_requests:approve',
  WFH_REQUESTS_REJECT: 'wfh_requests:reject',

  HOLIDAYS_CREATE: 'holidays:create',
  HOLIDAYS_READ: 'holidays:read',
  HOLIDAYS_UPDATE: 'holidays:update',
  HOLIDAYS_DELETE: 'holidays:delete',
  HOLIDAYS_CLAIM_OPTIONAL: 'holidays:claim_optional',

  EXPENSE_CATEGORIES_CREATE: 'expense_categories:create',
  EXPENSE_CATEGORIES_READ: 'expense_categories:read',
  EXPENSE_POLICIES_CREATE: 'expense_policies:create',
  EXPENSES_CREATE: 'expenses:create',
  EXPENSES_READ: 'expenses:read',
  EXPENSES_APPROVE: 'expenses:approve',
  EXPENSES_REJECT: 'expenses:reject',

  APPROVALS_PENDING_READ: 'approvals:pending:read',
  APPROVALS_HISTORY_READ: 'approvals:history:read',
  APPROVALS_APPROVE: 'approvals:approve',
  APPROVALS_REJECT: 'approvals:reject',
} as const;

export type PermissionCode =
  (typeof PERMISSIONS)[keyof typeof PERMISSIONS];
