import { Role } from '../enums/role.enum';
import { PERMISSIONS, type PermissionCode } from './permission.constants';

export const DEFAULT_ROLE_DEFINITIONS: Array<{
  code: Role;
  name: string;
  description: string;
}> = [
  {
    code: Role.SUPER_ADMIN,
    name: 'Super Admin',
    description: 'Full tenant administration access',
  },
  {
    code: Role.TEAM_LEAD,
    name: 'Team Lead',
    description: 'Team and project management access',
  },
  {
    code: Role.USER,
    name: 'User',
    description: 'Assigned work and self-service access',
  },
];

export const DEFAULT_PERMISSION_DEFINITIONS: Array<{
  code: PermissionCode;
  name: string;
  description: string;
}> = [
  {
    code: PERMISSIONS.TENANTS_CREATE,
    name: 'Create Tenant',
    description: 'Create tenant and onboarding owner',
  },
  {
    code: PERMISSIONS.TENANTS_READ_CURRENT,
    name: 'Read Current Tenant',
    description: 'Read current tenant details',
  },
  {
    code: PERMISSIONS.TENANT_SETTINGS_UPDATE,
    name: 'Update Tenant Settings',
    description: 'Update tenant settings',
  },
  { code: PERMISSIONS.USERS_CREATE, name: 'Create Users', description: 'Create users' },
  { code: PERMISSIONS.USERS_READ, name: 'Read Users', description: 'Read users' },
  { code: PERMISSIONS.USERS_UPDATE, name: 'Update Users', description: 'Update users' },
  { code: PERMISSIONS.USERS_DELETE, name: 'Delete Users', description: 'Delete users' },
  { code: PERMISSIONS.USERS_IMPORT, name: 'Import Users', description: 'Import users' },
  { code: PERMISSIONS.TEAMS_CREATE, name: 'Create Teams', description: 'Create teams' },
  { code: PERMISSIONS.TEAMS_READ, name: 'Read Teams', description: 'Read teams' },
  { code: PERMISSIONS.TEAMS_UPDATE, name: 'Update Teams', description: 'Update teams' },
  {
    code: PERMISSIONS.TEAMS_MEMBERS_WRITE,
    name: 'Manage Team Members',
    description: 'Add or remove team members',
  },
  {
    code: PERMISSIONS.USER_ROLES_ASSIGN,
    name: 'Assign User Roles',
    description: 'Assign roles to users',
  },
  { code: PERMISSIONS.ROLES_READ, name: 'Read Roles', description: 'Read roles' },
  {
    code: PERMISSIONS.PERMISSIONS_READ,
    name: 'Read Permissions',
    description: 'Read permissions',
  },
  {
    code: PERMISSIONS.OFFICE_LOCATIONS_CREATE,
    name: 'Create Office Locations',
    description: 'Create office locations',
  },
  {
    code: PERMISSIONS.OFFICE_LOCATIONS_READ,
    name: 'Read Office Locations',
    description: 'Read office locations',
  },
  {
    code: PERMISSIONS.OFFICE_IPS_CREATE,
    name: 'Create Office IP Rules',
    description: 'Create office IP allowlist entries',
  },
  {
    code: PERMISSIONS.OFFICE_IPS_READ,
    name: 'Read Office IP Rules',
    description: 'Read office IP allowlist entries',
  },
  {
    code: PERMISSIONS.OFFICE_POLICY_CHECK,
    name: 'Check Office Policy',
    description: 'Check office network policy access',
  },
  {
    code: PERMISSIONS.NOTIFICATION_SELF_READ,
    name: 'Read Own Notification Preferences',
    description: 'Read own notification preferences',
  },
  {
    code: PERMISSIONS.NOTIFICATION_SELF_UPDATE,
    name: 'Update Own Notification Preferences',
    description: 'Update own notification preferences',
  },

  { code: PERMISSIONS.PROJECTS_CREATE, name: 'Create Projects', description: 'Create projects' },
  { code: PERMISSIONS.PROJECTS_READ, name: 'Read Projects', description: 'Read projects' },
  { code: PERMISSIONS.PROJECTS_UPDATE, name: 'Update Projects', description: 'Update projects' },
  { code: PERMISSIONS.PROJECTS_DELETE, name: 'Delete Projects', description: 'Delete projects' },
  {
    code: PERMISSIONS.PROJECTS_MEMBERS_WRITE,
    name: 'Manage Project Members',
    description: 'Add project members',
  },
  {
    code: PERMISSIONS.PROJECTS_COSTS_WRITE,
    name: 'Add Project Costs',
    description: 'Add project cost entries',
  },
  {
    code: PERMISSIONS.PROJECTS_BURN_READ,
    name: 'Read Project Burn',
    description: 'Read project burn metrics',
  },
  {
    code: PERMISSIONS.PROJECTS_COST_SUMMARY_READ,
    name: 'Read Project Cost Summary',
    description: 'Read project cost summary metrics',
  },
  {
    code: PERMISSIONS.TIME_ENTRIES_CREATE,
    name: 'Create Time Entries',
    description: 'Create time entries',
  },
  {
    code: PERMISSIONS.TIME_ENTRIES_READ,
    name: 'Read Time Entries',
    description: 'Read time entries',
  },
  {
    code: PERMISSIONS.TIME_ENTRIES_ADJUST,
    name: 'Adjust Time Entries',
    description: 'Create time entry adjustments',
  },
  {
    code: PERMISSIONS.TIME_ENTRIES_UNLOCK,
    name: 'Unlock Time Entries',
    description: 'Unlock locked time entries with reason',
  },
  {
    code: PERMISSIONS.TIME_ENTRIES_SUMMARY_READ,
    name: 'Read Time Entry Summary',
    description: 'Read grouped time summary metrics',
  },
  {
    code: PERMISSIONS.TIME_ENTRIES_MANAGER_BULK,
    name: 'Manager Bulk Time Entry',
    description: 'Create bulk manager time entries',
  },

  {
    code: PERMISSIONS.MILESTONES_CREATE,
    name: 'Create Milestones',
    description: 'Create milestones',
  },
  {
    code: PERMISSIONS.MILESTONES_READ,
    name: 'Read Milestones',
    description: 'Read milestones',
  },
  {
    code: PERMISSIONS.MILESTONES_UPDATE,
    name: 'Update Milestones',
    description: 'Update milestones',
  },
  {
    code: PERMISSIONS.MILESTONES_DELETE,
    name: 'Delete Milestones',
    description: 'Delete milestones',
  },

  {
    code: PERMISSIONS.TASK_STATUSES_CREATE,
    name: 'Create Task Statuses',
    description: 'Create task statuses',
  },
  {
    code: PERMISSIONS.TASK_STATUSES_READ,
    name: 'Read Task Statuses',
    description: 'Read task statuses',
  },
  {
    code: PERMISSIONS.TASK_STATUSES_UPDATE,
    name: 'Update Task Statuses',
    description: 'Update task statuses',
  },
  {
    code: PERMISSIONS.TASK_STATUSES_DELETE,
    name: 'Delete Task Statuses',
    description: 'Delete task statuses',
  },

  {
    code: PERMISSIONS.TASK_WORKFLOWS_CREATE,
    name: 'Create Task Workflows',
    description: 'Create task workflows',
  },
  {
    code: PERMISSIONS.TASK_WORKFLOWS_READ,
    name: 'Read Task Workflows',
    description: 'Read task workflows',
  },

  { code: PERMISSIONS.TASKS_CREATE, name: 'Create Tasks', description: 'Create tasks' },
  { code: PERMISSIONS.TASKS_READ, name: 'Read Tasks', description: 'Read tasks' },
  { code: PERMISSIONS.TASKS_UPDATE, name: 'Update Tasks', description: 'Update tasks' },
  { code: PERMISSIONS.TASKS_DELETE, name: 'Delete Tasks', description: 'Delete tasks' },
  {
    code: PERMISSIONS.TASKS_STATUS_UPDATE,
    name: 'Update Task Status',
    description: 'Move task across statuses',
  },
  {
    code: PERMISSIONS.TASKS_KANBAN_READ,
    name: 'Read Task Kanban',
    description: 'Read task kanban view',
  },
  {
    code: PERMISSIONS.TASKS_BULK_UPDATE,
    name: 'Bulk Update Tasks',
    description: 'Bulk update task fields',
  },
  {
    code: PERMISSIONS.TASKS_DEPENDENCIES_WRITE,
    name: 'Manage Task Dependencies',
    description: 'Create and delete dependencies',
  },
  {
    code: PERMISSIONS.TASKS_COMMENTS_CREATE,
    name: 'Create Task Comments',
    description: 'Create task comments',
  },
  {
    code: PERMISSIONS.TASKS_COMMENTS_READ,
    name: 'Read Task Comments',
    description: 'Read task comments',
  },

  {
    code: PERMISSIONS.ATTACHMENTS_PRESIGNED_URL,
    name: 'Create Attachment Presigned URL',
    description: 'Request S3 upload URL for attachment',
  },
  {
    code: PERMISSIONS.ATTACHMENTS_CONFIRM_UPLOAD,
    name: 'Confirm Attachment Upload',
    description: 'Confirm uploaded attachment and persist metadata',
  },
  {
    code: PERMISSIONS.ATTACHMENTS_READ,
    name: 'Read Attachments',
    description: 'Read attachment metadata',
  },
  {
    code: PERMISSIONS.ATTENDANCE_CHECK_IN,
    name: 'Attendance Check-in',
    description: 'Create attendance check-in event',
  },
  {
    code: PERMISSIONS.ATTENDANCE_CHECK_OUT,
    name: 'Attendance Check-out',
    description: 'Create attendance check-out event',
  },
  {
    code: PERMISSIONS.ATTENDANCE_TODAY_READ,
    name: 'Read Attendance Today',
    description: 'Read current day attendance',
  },
  {
    code: PERMISSIONS.ATTENDANCE_REPORT_READ,
    name: 'Read Attendance Report',
    description: 'Read attendance reports',
  },
  {
    code: PERMISSIONS.ATTENDANCE_REGULARIZATION_CREATE,
    name: 'Create Attendance Regularization',
    description: 'Create regularization requests',
  },
  {
    code: PERMISSIONS.ATTENDANCE_REGULARIZATION_READ,
    name: 'Read Attendance Regularization',
    description: 'Read regularization requests',
  },
  {
    code: PERMISSIONS.ATTENDANCE_REGULARIZATION_APPROVE,
    name: 'Approve Attendance Regularization',
    description: 'Approve regularization requests',
  },
  {
    code: PERMISSIONS.ATTENDANCE_REGULARIZATION_REJECT,
    name: 'Reject Attendance Regularization',
    description: 'Reject regularization requests',
  },
  {
    code: PERMISSIONS.LEAVE_TYPES_CREATE,
    name: 'Create Leave Types',
    description: 'Create leave types',
  },
  {
    code: PERMISSIONS.LEAVE_TYPES_READ,
    name: 'Read Leave Types',
    description: 'Read leave types',
  },
  {
    code: PERMISSIONS.LEAVE_POLICIES_CREATE,
    name: 'Create Leave Policies',
    description: 'Create leave policies and overrides',
  },
  {
    code: PERMISSIONS.LEAVE_BALANCE_ME_READ,
    name: 'Read Own Leave Balance',
    description: 'Read own leave balance',
  },
  {
    code: PERMISSIONS.LEAVE_BALANCE_USER_READ,
    name: 'Read User Leave Balance',
    description: 'Read leave balances by user',
  },
  {
    code: PERMISSIONS.LEAVE_REQUESTS_CREATE,
    name: 'Create Leave Requests',
    description: 'Create leave requests',
  },
  {
    code: PERMISSIONS.LEAVE_REQUESTS_READ,
    name: 'Read Leave Requests',
    description: 'Read leave requests',
  },
  {
    code: PERMISSIONS.LEAVE_REQUESTS_APPROVE,
    name: 'Approve Leave Requests',
    description: 'Approve leave requests',
  },
  {
    code: PERMISSIONS.LEAVE_REQUESTS_REJECT,
    name: 'Reject Leave Requests',
    description: 'Reject leave requests',
  },
  {
    code: PERMISSIONS.WFH_POLICIES_CREATE,
    name: 'Create WFH Policies',
    description: 'Create WFH policies and overrides',
  },
  {
    code: PERMISSIONS.WFH_BALANCE_ME_READ,
    name: 'Read Own WFH Balance',
    description: 'Read own WFH balance',
  },
  {
    code: PERMISSIONS.WFH_BALANCE_USER_READ,
    name: 'Read User WFH Balance',
    description: 'Read WFH balances by user',
  },
  {
    code: PERMISSIONS.WFH_REQUESTS_CREATE,
    name: 'Create WFH Requests',
    description: 'Create WFH requests',
  },
  {
    code: PERMISSIONS.WFH_REQUESTS_READ,
    name: 'Read WFH Requests',
    description: 'Read WFH requests',
  },
  {
    code: PERMISSIONS.WFH_REQUESTS_APPROVE,
    name: 'Approve WFH Requests',
    description: 'Approve WFH requests',
  },
  {
    code: PERMISSIONS.WFH_REQUESTS_REJECT,
    name: 'Reject WFH Requests',
    description: 'Reject WFH requests',
  },
  {
    code: PERMISSIONS.HOLIDAYS_CREATE,
    name: 'Create Holidays',
    description: 'Create holidays',
  },
  {
    code: PERMISSIONS.HOLIDAYS_READ,
    name: 'Read Holidays',
    description: 'Read holidays',
  },
  {
    code: PERMISSIONS.HOLIDAYS_UPDATE,
    name: 'Update Holidays',
    description: 'Update holidays',
  },
  {
    code: PERMISSIONS.HOLIDAYS_DELETE,
    name: 'Delete Holidays',
    description: 'Delete holidays',
  },
  {
    code: PERMISSIONS.HOLIDAYS_CLAIM_OPTIONAL,
    name: 'Claim Optional Holiday',
    description: 'Claim optional holidays',
  },
  {
    code: PERMISSIONS.EXPENSE_CATEGORIES_CREATE,
    name: 'Create Expense Categories',
    description: 'Create expense categories',
  },
  {
    code: PERMISSIONS.EXPENSE_CATEGORIES_READ,
    name: 'Read Expense Categories',
    description: 'Read expense categories',
  },
  {
    code: PERMISSIONS.EXPENSE_POLICIES_CREATE,
    name: 'Create Expense Policies',
    description: 'Create expense policies',
  },
  {
    code: PERMISSIONS.EXPENSES_CREATE,
    name: 'Create Expenses',
    description: 'Create expense requests',
  },
  {
    code: PERMISSIONS.EXPENSES_READ,
    name: 'Read Expenses',
    description: 'Read expenses',
  },
  {
    code: PERMISSIONS.EXPENSES_APPROVE,
    name: 'Approve Expenses',
    description: 'Approve expense requests',
  },
  {
    code: PERMISSIONS.EXPENSES_REJECT,
    name: 'Reject Expenses',
    description: 'Reject expense requests',
  },
  {
    code: PERMISSIONS.APPROVALS_PENDING_READ,
    name: 'Read Pending Approvals',
    description: 'Read pending approvals',
  },
  {
    code: PERMISSIONS.APPROVALS_HISTORY_READ,
    name: 'Read Approval History',
    description: 'Read approval history',
  },
  {
    code: PERMISSIONS.APPROVALS_APPROVE,
    name: 'Approve Requests',
    description: 'Approve approval requests',
  },
  {
    code: PERMISSIONS.APPROVALS_REJECT,
    name: 'Reject Requests',
    description: 'Reject approval requests',
  },
  {
    code: PERMISSIONS.NOTIFICATIONS_SEND,
    name: 'Send Notifications',
    description: 'Create notification events and deliveries',
  },
  {
    code: PERMISSIONS.NOTIFICATIONS_READ,
    name: 'Read Notifications',
    description: 'Read own notification inbox',
  },
  {
    code: PERMISSIONS.NOTIFICATIONS_MARK_READ,
    name: 'Mark Notifications Read',
    description: 'Mark own notifications as read',
  },
  {
    code: PERMISSIONS.INTEGRATIONS_GITHUB_SETTINGS_WRITE,
    name: 'Manage GitHub Settings',
    description: 'Create/update GitHub integration settings',
  },
  {
    code: PERMISSIONS.INTEGRATIONS_GITHUB_SETTINGS_READ,
    name: 'Read GitHub Settings',
    description: 'Read GitHub integration settings',
  },
  {
    code: PERMISSIONS.INTEGRATIONS_GITHUB_UNMATCHED_READ,
    name: 'Read GitHub Unmatched Commits',
    description: 'Read unmatched GitHub commits',
  },
  {
    code: PERMISSIONS.INTEGRATIONS_GITHUB_UNMATCHED_MAP,
    name: 'Map GitHub Unmatched Commits',
    description: 'Map unmatched GitHub commits to tasks',
  },
  {
    code: PERMISSIONS.INTEGRATIONS_GITHUB_EVENTS_READ,
    name: 'Read GitHub Events',
    description: 'Read GitHub webhook events',
  },
  {
    code: PERMISSIONS.INTEGRATIONS_SLACK_SETTINGS_WRITE,
    name: 'Manage Slack Settings',
    description: 'Create/update Slack integration settings',
  },
  {
    code: PERMISSIONS.INTEGRATIONS_EMAIL_SETTINGS_WRITE,
    name: 'Manage Email Settings',
    description: 'Create/update email integration settings',
  },
  {
    code: PERMISSIONS.INTEGRATIONS_WHATSAPP_TEMPLATE_SEND,
    name: 'Send WhatsApp Templates',
    description: 'Send WhatsApp utility templates',
  },
  {
    code: PERMISSIONS.INTEGRATIONS_WHATSAPP_SESSIONS_READ,
    name: 'Read WhatsApp Sessions',
    description: 'Read WhatsApp sessions',
  },
  {
    code: PERMISSIONS.INTEGRATIONS_WHATSAPP_MESSAGES_READ,
    name: 'Read WhatsApp Messages',
    description: 'Read WhatsApp messages',
  },
  {
    code: PERMISSIONS.AI_CHAT,
    name: 'AI Chat',
    description: 'Use AI chat assistant endpoint',
  },
  {
    code: PERMISSIONS.AI_TOOLS_READ,
    name: 'Read AI Tool Catalog',
    description: 'Read AI tool registry metadata',
  },
  {
    code: PERMISSIONS.AI_MESSAGES_READ,
    name: 'Read AI Messages',
    description: 'Read AI chat history',
  },
  {
    code: PERMISSIONS.DOCUMENTS_CREATE,
    name: 'Create Documents',
    description: 'Create tenant document sources',
  },
  {
    code: PERMISSIONS.DOCUMENTS_READ,
    name: 'Read Documents',
    description: 'Read tenant document sources',
  },
  {
    code: PERMISSIONS.DOCUMENTS_SEARCH,
    name: 'Search Documents',
    description: 'Run tenant-scoped document search',
  },
  {
    code: PERMISSIONS.DOCUMENTS_DELETE,
    name: 'Delete Documents',
    description: 'Delete tenant document sources',
  },
  {
    code: PERMISSIONS.DASHBOARD_SUPER_ADMIN_READ,
    name: 'Read Super Admin Dashboard',
    description: 'Read tenant-wide KPI dashboard',
  },
  {
    code: PERMISSIONS.DASHBOARD_TEAM_LEAD_READ,
    name: 'Read Team Lead Dashboard',
    description: 'Read team-scoped KPI dashboard',
  },
  {
    code: PERMISSIONS.DASHBOARD_USER_PERFORMANCE_READ,
    name: 'Read User Performance Dashboard',
    description: 'Read scoped user performance KPIs',
  },
  {
    code: PERMISSIONS.DASHBOARD_PROJECT_READ,
    name: 'Read Project Dashboard',
    description: 'Read project KPI dashboard',
  },
  {
    code: PERMISSIONS.REVIEW_CYCLES_CREATE,
    name: 'Create Review Cycles',
    description: 'Create monthly review cycles',
  },
  {
    code: PERMISSIONS.REVIEW_CYCLES_READ,
    name: 'Read Review Cycles',
    description: 'Read monthly review cycles',
  },
  {
    code: PERMISSIONS.REVIEWS_CREATE,
    name: 'Create Reviews',
    description: 'Create review entries',
  },
  {
    code: PERMISSIONS.REVIEWS_READ,
    name: 'Read Reviews',
    description: 'Read review entries',
  },
  {
    code: PERMISSIONS.REVIEWS_SUBMIT,
    name: 'Submit Reviews',
    description: 'Submit review entries',
  },
  {
    code: PERMISSIONS.REVIEWS_APPROVE,
    name: 'Approve Reviews',
    description: 'Approve submitted review entries',
  },
  {
    code: PERMISSIONS.AUDIT_LOGS_READ,
    name: 'Read Audit Logs',
    description: 'Read tenant audit logs',
  },
  {
    code: PERMISSIONS.COMPLIANCE_DATA_EXPORT_CREATE,
    name: 'Create Compliance Data Export Requests',
    description: 'Create self-service data export requests',
  },
  {
    code: PERMISSIONS.COMPLIANCE_DATA_ERASURE_CREATE,
    name: 'Create Compliance Data Erasure Requests',
    description: 'Create self-service data erasure requests',
  },
  {
    code: PERMISSIONS.COMPLIANCE_REQUESTS_READ,
    name: 'Read Compliance Requests',
    description: 'Read compliance requests in allowed scope',
  },
];

export const DEFAULT_ROLE_PERMISSION_CODES: Record<Role, PermissionCode[]> = {
  [Role.SUPER_ADMIN]: DEFAULT_PERMISSION_DEFINITIONS.map((entry) => entry.code),
  [Role.TEAM_LEAD]: [
    PERMISSIONS.TENANTS_READ_CURRENT,
    PERMISSIONS.USERS_CREATE,
    PERMISSIONS.USERS_READ,
    PERMISSIONS.USERS_UPDATE,
    PERMISSIONS.USERS_IMPORT,
    PERMISSIONS.TEAMS_CREATE,
    PERMISSIONS.TEAMS_READ,
    PERMISSIONS.TEAMS_UPDATE,
    PERMISSIONS.TEAMS_MEMBERS_WRITE,
    PERMISSIONS.USER_ROLES_ASSIGN,
    PERMISSIONS.ROLES_READ,
    PERMISSIONS.PERMISSIONS_READ,
    PERMISSIONS.OFFICE_LOCATIONS_CREATE,
    PERMISSIONS.OFFICE_LOCATIONS_READ,
    PERMISSIONS.OFFICE_IPS_CREATE,
    PERMISSIONS.OFFICE_IPS_READ,
    PERMISSIONS.OFFICE_POLICY_CHECK,
    PERMISSIONS.NOTIFICATION_SELF_READ,
    PERMISSIONS.NOTIFICATION_SELF_UPDATE,
    PERMISSIONS.PROJECTS_CREATE,
    PERMISSIONS.PROJECTS_READ,
    PERMISSIONS.PROJECTS_UPDATE,
    PERMISSIONS.PROJECTS_DELETE,
    PERMISSIONS.PROJECTS_MEMBERS_WRITE,
    PERMISSIONS.PROJECTS_COSTS_WRITE,
    PERMISSIONS.PROJECTS_BURN_READ,
    PERMISSIONS.PROJECTS_COST_SUMMARY_READ,
    PERMISSIONS.TIME_ENTRIES_CREATE,
    PERMISSIONS.TIME_ENTRIES_READ,
    PERMISSIONS.TIME_ENTRIES_ADJUST,
    PERMISSIONS.TIME_ENTRIES_UNLOCK,
    PERMISSIONS.TIME_ENTRIES_SUMMARY_READ,
    PERMISSIONS.TIME_ENTRIES_MANAGER_BULK,
    PERMISSIONS.MILESTONES_CREATE,
    PERMISSIONS.MILESTONES_READ,
    PERMISSIONS.MILESTONES_UPDATE,
    PERMISSIONS.MILESTONES_DELETE,
    PERMISSIONS.TASK_STATUSES_CREATE,
    PERMISSIONS.TASK_STATUSES_READ,
    PERMISSIONS.TASK_STATUSES_UPDATE,
    PERMISSIONS.TASK_STATUSES_DELETE,
    PERMISSIONS.TASK_WORKFLOWS_CREATE,
    PERMISSIONS.TASK_WORKFLOWS_READ,
    PERMISSIONS.TASKS_CREATE,
    PERMISSIONS.TASKS_READ,
    PERMISSIONS.TASKS_UPDATE,
    PERMISSIONS.TASKS_DELETE,
    PERMISSIONS.TASKS_STATUS_UPDATE,
    PERMISSIONS.TASKS_KANBAN_READ,
    PERMISSIONS.TASKS_BULK_UPDATE,
    PERMISSIONS.TASKS_DEPENDENCIES_WRITE,
    PERMISSIONS.TASKS_COMMENTS_CREATE,
    PERMISSIONS.TASKS_COMMENTS_READ,
    PERMISSIONS.ATTACHMENTS_PRESIGNED_URL,
    PERMISSIONS.ATTACHMENTS_CONFIRM_UPLOAD,
    PERMISSIONS.ATTACHMENTS_READ,
    PERMISSIONS.ATTENDANCE_CHECK_IN,
    PERMISSIONS.ATTENDANCE_CHECK_OUT,
    PERMISSIONS.ATTENDANCE_TODAY_READ,
    PERMISSIONS.ATTENDANCE_REPORT_READ,
    PERMISSIONS.ATTENDANCE_REGULARIZATION_CREATE,
    PERMISSIONS.ATTENDANCE_REGULARIZATION_READ,
    PERMISSIONS.ATTENDANCE_REGULARIZATION_APPROVE,
    PERMISSIONS.ATTENDANCE_REGULARIZATION_REJECT,
    PERMISSIONS.LEAVE_TYPES_CREATE,
    PERMISSIONS.LEAVE_TYPES_READ,
    PERMISSIONS.LEAVE_POLICIES_CREATE,
    PERMISSIONS.LEAVE_BALANCE_ME_READ,
    PERMISSIONS.LEAVE_BALANCE_USER_READ,
    PERMISSIONS.LEAVE_REQUESTS_CREATE,
    PERMISSIONS.LEAVE_REQUESTS_READ,
    PERMISSIONS.LEAVE_REQUESTS_APPROVE,
    PERMISSIONS.LEAVE_REQUESTS_REJECT,
    PERMISSIONS.WFH_POLICIES_CREATE,
    PERMISSIONS.WFH_BALANCE_ME_READ,
    PERMISSIONS.WFH_BALANCE_USER_READ,
    PERMISSIONS.WFH_REQUESTS_CREATE,
    PERMISSIONS.WFH_REQUESTS_READ,
    PERMISSIONS.WFH_REQUESTS_APPROVE,
    PERMISSIONS.WFH_REQUESTS_REJECT,
    PERMISSIONS.HOLIDAYS_CREATE,
    PERMISSIONS.HOLIDAYS_READ,
    PERMISSIONS.HOLIDAYS_UPDATE,
    PERMISSIONS.HOLIDAYS_DELETE,
    PERMISSIONS.HOLIDAYS_CLAIM_OPTIONAL,
    PERMISSIONS.EXPENSE_CATEGORIES_CREATE,
    PERMISSIONS.EXPENSE_CATEGORIES_READ,
    PERMISSIONS.EXPENSE_POLICIES_CREATE,
    PERMISSIONS.EXPENSES_CREATE,
    PERMISSIONS.EXPENSES_READ,
    PERMISSIONS.EXPENSES_APPROVE,
    PERMISSIONS.EXPENSES_REJECT,
    PERMISSIONS.APPROVALS_PENDING_READ,
    PERMISSIONS.APPROVALS_HISTORY_READ,
    PERMISSIONS.APPROVALS_APPROVE,
    PERMISSIONS.APPROVALS_REJECT,
    PERMISSIONS.NOTIFICATIONS_SEND,
    PERMISSIONS.NOTIFICATIONS_READ,
    PERMISSIONS.NOTIFICATIONS_MARK_READ,
    PERMISSIONS.INTEGRATIONS_GITHUB_SETTINGS_WRITE,
    PERMISSIONS.INTEGRATIONS_GITHUB_SETTINGS_READ,
    PERMISSIONS.INTEGRATIONS_GITHUB_UNMATCHED_READ,
    PERMISSIONS.INTEGRATIONS_GITHUB_UNMATCHED_MAP,
    PERMISSIONS.INTEGRATIONS_GITHUB_EVENTS_READ,
    PERMISSIONS.INTEGRATIONS_SLACK_SETTINGS_WRITE,
    PERMISSIONS.INTEGRATIONS_EMAIL_SETTINGS_WRITE,
    PERMISSIONS.INTEGRATIONS_WHATSAPP_TEMPLATE_SEND,
    PERMISSIONS.INTEGRATIONS_WHATSAPP_SESSIONS_READ,
    PERMISSIONS.INTEGRATIONS_WHATSAPP_MESSAGES_READ,
    PERMISSIONS.DASHBOARD_TEAM_LEAD_READ,
    PERMISSIONS.DASHBOARD_USER_PERFORMANCE_READ,
    PERMISSIONS.DASHBOARD_PROJECT_READ,
    PERMISSIONS.REVIEW_CYCLES_CREATE,
    PERMISSIONS.REVIEW_CYCLES_READ,
    PERMISSIONS.REVIEWS_CREATE,
    PERMISSIONS.REVIEWS_READ,
    PERMISSIONS.REVIEWS_SUBMIT,
    PERMISSIONS.COMPLIANCE_DATA_EXPORT_CREATE,
    PERMISSIONS.COMPLIANCE_DATA_ERASURE_CREATE,
    PERMISSIONS.COMPLIANCE_REQUESTS_READ,
    PERMISSIONS.AI_CHAT,
    PERMISSIONS.AI_TOOLS_READ,
    PERMISSIONS.AI_MESSAGES_READ,
    PERMISSIONS.DOCUMENTS_CREATE,
    PERMISSIONS.DOCUMENTS_READ,
    PERMISSIONS.DOCUMENTS_SEARCH,
    PERMISSIONS.DOCUMENTS_DELETE,
  ],
  [Role.USER]: [
    PERMISSIONS.TENANTS_READ_CURRENT,
    PERMISSIONS.OFFICE_POLICY_CHECK,
    PERMISSIONS.NOTIFICATION_SELF_READ,
    PERMISSIONS.NOTIFICATION_SELF_UPDATE,
    PERMISSIONS.TASKS_READ,
    PERMISSIONS.TASKS_UPDATE,
    PERMISSIONS.TASKS_STATUS_UPDATE,
    PERMISSIONS.TASKS_KANBAN_READ,
    PERMISSIONS.TASKS_COMMENTS_CREATE,
    PERMISSIONS.TASKS_COMMENTS_READ,
    PERMISSIONS.ATTACHMENTS_READ,
    PERMISSIONS.TIME_ENTRIES_CREATE,
    PERMISSIONS.TIME_ENTRIES_READ,
    PERMISSIONS.TIME_ENTRIES_ADJUST,
    PERMISSIONS.TIME_ENTRIES_SUMMARY_READ,
    PERMISSIONS.ATTENDANCE_CHECK_IN,
    PERMISSIONS.ATTENDANCE_CHECK_OUT,
    PERMISSIONS.ATTENDANCE_TODAY_READ,
    PERMISSIONS.ATTENDANCE_REPORT_READ,
    PERMISSIONS.ATTENDANCE_REGULARIZATION_CREATE,
    PERMISSIONS.ATTENDANCE_REGULARIZATION_READ,
    PERMISSIONS.LEAVE_TYPES_READ,
    PERMISSIONS.LEAVE_BALANCE_ME_READ,
    PERMISSIONS.LEAVE_REQUESTS_CREATE,
    PERMISSIONS.LEAVE_REQUESTS_READ,
    PERMISSIONS.WFH_BALANCE_ME_READ,
    PERMISSIONS.WFH_REQUESTS_CREATE,
    PERMISSIONS.WFH_REQUESTS_READ,
    PERMISSIONS.HOLIDAYS_READ,
    PERMISSIONS.HOLIDAYS_CLAIM_OPTIONAL,
    PERMISSIONS.EXPENSE_CATEGORIES_READ,
    PERMISSIONS.EXPENSES_CREATE,
    PERMISSIONS.EXPENSES_READ,
    PERMISSIONS.NOTIFICATIONS_READ,
    PERMISSIONS.NOTIFICATIONS_MARK_READ,
    PERMISSIONS.DASHBOARD_USER_PERFORMANCE_READ,
    PERMISSIONS.DASHBOARD_PROJECT_READ,
    PERMISSIONS.REVIEW_CYCLES_READ,
    PERMISSIONS.REVIEWS_READ,
    PERMISSIONS.COMPLIANCE_DATA_EXPORT_CREATE,
    PERMISSIONS.COMPLIANCE_DATA_ERASURE_CREATE,
    PERMISSIONS.COMPLIANCE_REQUESTS_READ,
    PERMISSIONS.AI_CHAT,
    PERMISSIONS.AI_TOOLS_READ,
    PERMISSIONS.AI_MESSAGES_READ,
    PERMISSIONS.DOCUMENTS_READ,
    PERMISSIONS.DOCUMENTS_SEARCH,
  ],
};
